base_url = "http://sid555.com/"
title = "Unloading..."
description = "Loading..."
theme = "draczola-bear"
generate_feeds = true
# The filenames to use for the feeds. Used as the template filenames, too.
# Defaults to ["atom.xml"], which has a built-in template that renders an Atom 1.0 feed.
# There is also a built-in template "rss.xml" that renders an RSS 2.0 feed.
feed_filenames = ["atom.xml"]
author = "Siddhant Laddha"
taxonomies = [
  { name = "tags", feed = true },
]
build_search_index = true
generate_sitemap = false

# Configuration of the Markdown rendering
[markdown]
external_links_target_blank = true
external_links_no_referrer = false
bottom_footnotes = true
# This determines whether to insert a link for each header like the ones you can see on this site if you hover over
# a header.
# The default template can be overridden by creating an `anchor-link.html` file in the `templates` directory.
# This value can be "left", "right", "heading" or "none".
# "heading" means the full heading becomes the text of the anchor.
# See "Internal links & deep linking" in the documentation for more information.
insert_anchor_links = "none"
# Syntax highlighting
[markdown.highlighting]
error_on_missing_language = true
theme = "dracula"
[search]
include_description = true
truncate_content_length = 100
index_format = "elasticlunr_javascript"
[translations]
no_posts = "No posts yet"
remove_filter = "Remove filter"
filtering_for = "Filtering for"
made_with = "Made with"
table_of_contents = "Table of contents"
language = "language"
site = "site"
[extra]
date_format = "%Y-%m-%d"
language_switcher = false
translations = [
  { code = "en", name = "English" },
]
hide_made_with_line = true
show_copyright_in_footer = true
[extra.table_of_contents]
show = true
max_level = 2
visible_on_load = false
[[extra.main_menu]]
name = "Home"
url = "@/_index.md"

[[extra.main_menu]]
name = "About Me"
url = "@/about_me.md"

[[extra.main_menu]]
name = "Blog"
url = "@/blog/_index.md"
