title = "Unloading..."
base_url = "https://siddhantladdha.com"
description = "Loading..."
author = "Siddhant Laddha"
theme = "draczola-bear"

taxonomies = [
  { name = "tags", feed = true },
]

[translations]
no_posts = "No posts yet"
remove_filter = "Remove filter"
filtering_for = "Filtering for"
made_with = "Made with"
table_of_contents = "Table of contents"
language = "language"
site = "site"

[markdown.highlighting]
error_on_missing_language = true

[extra]
date_format = "%Y-%m-%d"
language_switcher = false
translations = [
  { code = "en", name = "English" },
]
hide_made_with_line = true
show_copyright_in_footer = true
[extra.table_of_contents]
show = true
max_level = 2
visible_on_load = false

[[extra.main_menu]]
name = "Home"
url = "@/_index.md"

[[extra.main_menu]]
name = "About Me"
url = "@/about_me.md"

[[extra.main_menu]]
name = "Blog"
url = "@/blog/_index.md"